version: '3'

services:
  php:
    image: andreescuc/warehouse_management_web_server
    network_mode: "host"

  cron:
    image: andreescuc/warehouse_management_cron

  client:
    image: andreescuc/warehouse_management_client_app
    volumes:
      - $HOME/.Xauthority:/root/.Xauthority
    environment:
      DISPLAY: $DISPLAY
    network_mode: "host"

  mysql:
    image: andreescuc/warehouse_management_mysql
    ports:
      - "3307:3306"

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "8002:15672"
      - "8003:5672"
